import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-activity/dist/library.css";
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookiesession = cookies();
  const tokenValue = cookiesession.get("token")?.value || null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar token={tokenValue} />
        {children}
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={true}
          cross
          theme="dark"
          limit={1}
          closeButton={false}
        />
      </body>
    </html>
  );
}
